### ISSUE TITLE
Wrong cuda API invoke

### ISSUE THREAD

**Issue by SydianAndrewChen** [bokesyo/CSC4005_2022Fall_Demo#31]
Code below is refered in template of project3:
```cuda
cudaMalloc(&device_m, n_body);
cudaMalloc(&device_x, n_body);
cudaMalloc(&device_y, n_body);
cudaMalloc(&device_vx, n_body);
cudaMalloc(&device_vy, n_body);

cudaMemcpy(device_m, m, n_body, cudaMemcpyHostToDevice);
cudaMemcpy(device_x, x, n_body, cudaMemcpyHostToDevice);
cudaMemcpy(device_y, y, n_body, cudaMemcpyHostToDevice);
cudaMemcpy(device_vx, vx, n_body, cudaMemcpyHostToDevice);
cudaMemcpy(device_vy, vy, n_body, cudaMemcpyHostToDevice);
```

However, the invoke of cudaMalloc API seems to be wrong. As [the official documentation of cuda](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__MEMORY.html#group__CUDART__MEMORY_1g37d37965bfb4803b6d4e59ff26856356) says: 
![image](https://user-images.githubusercontent.com/65159293/201324490-ed63010c-ecb1-4c73-96d3-a6477ea032a2.png)

The parameter here should be in **bytes**.

Thus, the API should be invoked as: 
```cuda
cudaMalloc(&device_m, n_body * sizeof(double));
cudaMalloc(&device_x, n_body * sizeof(double));
cudaMalloc(&device_y, n_body * sizeof(double));
cudaMalloc(&device_vx, n_body * sizeof(double));
cudaMalloc(&device_vy, n_body * sizeof(double));

cudaMemcpy(device_m, m, n_body * sizeof(double), cudaMemcpyHostToDevice);
cudaMemcpy(device_x, x, n_body * sizeof(double), cudaMemcpyHostToDevice);
cudaMemcpy(device_y, y, n_body * sizeof(double), cudaMemcpyHostToDevice);
cudaMemcpy(device_vx, vx, n_body * sizeof(double), cudaMemcpyHostToDevice);
cudaMemcpy(device_vy, vy, n_body * sizeof(double), cudaMemcpyHostToDevice);
```

This is a prboblem of template, so I am afraid it might affect a lot of students, as I have already wasted much time finding this bug. Please quickly correct them. @bokesyo

**Comment by bokesyo** [comment]
Thank you!

**Comment by bokesyo** [comment]
Now i have made PR to fix this problem! Thank you again!
