### ISSUE TITLE
advice: reinstall nvidia driver

### ISSUE THREAD

**Issue by fourdim** [bokesyo/CSC4005_2022Fall_Demo#9]
__glapi_tls_current has been introduced since 2013.
https://github.com/NVIDIA/libglvnd/commit/efa8ca15c54d82b396cc1c401de21b525c67d892
Different commits may have different ABIs, which are not compatible.
It's likely that centos pack the cuda and libglvnd-dev with different commits. A simple reinstallation of cuda with `--install-libglvnd` will likely to solve this.
https://download.nvidia.com/XFree86/Linux-x86_64/450.80.02/README/installedcomponents.html
Installation guide using the cuda repo:
https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#redhat-installation
This is just a guess; hope it will be useful.

**Comment by tonyyxliu** [comment]
Hi fourdim,
    Thank you for your advice helping us fix this error. I have tried to reinstall the `libglvnd` package as you said and the error of  "glapi_tls_current" was indeed fixed. By connecting to the cluster with MobaXterm, we are now able to see the expected output display of many commands for testing like `xclock`, `xeyes`, and `glxgears`, but I am still stuck by the problem that the user-implemented OpenGL programs always display a black screen. I am very curious about whether that is the case on your computer.
    Thank you again for your advice, and that really helps me a lot.
